version: '3.8'
services:
  mysql:
    image: mysql:latest
    restart: on-failure
    container_name: mysql_airports
    environment:
      MYSQL_ROOT_USERNAME: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: airports_db
    ports:
      - "3306:3306"
    security_opt:
      - seccomp:unconfined
    networks:
      - my-network

  airports-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: airports-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_airports:3306/airports_db?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - mysql_airports
    volumes:
      - ./src/main/resources/airports.csv:/src/main/resources/airports.csv
      - ./src/main/resources/flights.csv:/src/main/resources/flights.csv
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
    external: false